services:
  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "corepack enable && corepack prepare pnpm@9.7.1 --activate && pnpm install && pnpm dev --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
